language: elixir
dist: zenial
elixir:
  - 1.9.4
otp_release:
  - 21.1
addons:
  postgresql: '9.5'
services:
  - postgresql
before_script:
  - gem install coveralls-multi --no-document
  - cp config/test.exs.travis config/test.exs
  - MIX_ENV=test mix ecto.create
script:
  - MIX_ENV=test mix coveralls.json
  - coveralls-multi
deploy:
  skip_cleanup: true
  provider: script
  script: mix hex.publish --yes
  on:
    tags: true
