language: elixir
dist: xenial
elixir:
  - 1.11.4
otp_release:
  - 24
addons:
  postgresql: '9.5'
services:
  - postgresql
before_script:
  - cp config/test.exs.travis config/test.exs
  - MIX_ENV=test mix ecto.create
script:
  - MIX_ENV=test mix test
deploy:
  skip_cleanup: true
  provider: script
  script: mix hex.publish --yes
  on:
    tags: true
